#!/usr/bin/env node
// packages/cli/scripts/generate-version.mjs
// Reads version from packages/cli/package.json and writes
// packages/cli/src/generated/version.ts (gitignored).
// Plain Node ESM — runs in any environment with Node 18+, no Bun required.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgPath = resolve(__dirname, "../package.json");
const outPath = resolve(__dirname, "../src/generated/version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
if (typeof pkg.version !== "string") {
  throw new Error(`package.json at ${pkgPath} has no string "version" field`);
}

// Public PostHog project token for anonymous CLI telemetry. Injected at release
// build via RB_POSTHOG_KEY; empty in dev/source (telemetry stays disabled).
// A PostHog project token is a write-only ingestion key — safe to embed in a
// distributed binary, same as it is embedded in a web page.
const telemetryKey = process.env.RB_POSTHOG_KEY ?? "";

const content = `// AUTO-GENERATED by scripts/generate-version.mjs — DO NOT EDIT.
export const VERSION = ${JSON.stringify(pkg.version)};
export const TELEMETRY_KEY = ${JSON.stringify(telemetryKey)};
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, content);
console.log(`Wrote ${outPath} with VERSION="${pkg.version}"${telemetryKey ? " + telemetry key" : ""}`);
